# Generated by Django 2.2.24 on 2025-01-09 16:57

from django.db import migrations


def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        phone_number = flat.owners_phonenumber
        normalized_phone = flat.owner_pure_phone
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            defaults={'phonenumber': phone_number, 'pure_phone': normalized_phone}
        )
        owner.flat.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(create_owners)
    ]
